### ISSUE TITLE
change default name of options to kebab-case

### ISSUE THREAD

**Issue by tacman** [zenstruck/console-extra#41]
```php
        #[Option(description: 'do not actually update')] // default name: 'dry-run' ? 
        bool    $dryRun,
```
It seems to me that the default name should be 'dry-run', since I don't think camelCase is used as frequently.

https://commons.apache.org/proper/commons-cli/

```
bin/console do:something --dryRun
bin/console do:something --dry-run
```

All Symfony commands:

```
  -n, --no-interaction  Do not ask any interactive question
  -e, --env=ENV         The Environment name. [default: "dev"]
      --no-debug        Switch off debug mode.
```

Of course, that's a BC change.

**Comment by kbond** [comment]
Good idea, I'll add to my 2.0 checklist

**Comment by tacman** [comment]
I see that this is coming, indeed I submitted a request for a more detailed deprecation warning #67
