### ISSUE TITLE
export command as string that can be run on the command line

### ISSUE THREAD

**Issue by tacman** [zenstruck/console-extra#51]
When a command fails, I'd like to dump it and run it in my own terminal, as errors are easier to see.  Is there a way to expand  a comand so I can see the arguments and parameters?

```php
        $command = $this->getApplication()->find('liip:imagine:cache:resolve');

        $arguments = [
            'paths' => [$path],
            '--filter' => $filter,
            '--force' => $force,
            '-vv' => true,
        ];

        $greetInput = new ArrayInput($arguments);
        $returnCode = $command->run($greetInput, $output);
        if ($returnCode) {
             // how can I print liip:imagine:cache:resolve $paths --filter=$filter, etc. so I can cut and paste it to the command line?
            assert(false, $path . ' returned ' . $returnCode);
        }
```

**Comment by kbond** [comment]
When running command's problematically, I always use `StringInput` so I can access the proper string it was run with.

**Comment by kbond** [comment]
Looks like `InputInterface` has a `__toString()` method as of [Symfony 6.1](https://github.com/symfony/symfony/pull/44746).

You should be able to use `(string) $greetInput` in your example above.

**Comment by tacman** [comment]
Yep!  I missed that, thanks!
