### ISSUE TITLE
Add option to wait until `runCommand` finishes

### ISSUE THREAD

**Issue by FluffyDiscord** [zenstruck/console-extra#53]
I have very simple helper command:

```php
<?php

namespace App\Command;

use Doctrine\Migrations\Tools\Console\Command\DiffCommand;
use Symfony\Component\Console\Attribute\AsCommand;
use Zenstruck\Console\InvokableServiceCommand;
use Zenstruck\Console\RunsCommands;

#[AsCommand(name: "migrate")]
class MigrateCommand extends InvokableServiceCommand
{
    use RunsCommands;

    public function __invoke(): void
    {
        $this->runCommand(DiffCommand::class . " --allow-empty-diff");
        $this->runCommand(\Doctrine\Migrations\Tools\Console\Command\MigrateCommand::class . " --no-interaction");
    }
}
```

The issue is that the `Migrate` command executes/finishes faster than the `Diff` command - they seem to run asynchronously. Can I run them in sync, one after another?

**Comment by kbond** [comment]
They are run synchronously 🤔, here are some ideas:

1. Could the second command be running too quickly after the first? Maybe try a sleep in between?
2. Can you confirm the `DiffCommand` is generated the required migration file?
3. I think the likely culprit is you can't run the `MigrateCommand` in the same process as the `DiffCommand`. `DiffCommand` generates a new php file which isn't autoloaded, therefore not picked up by `MigrationCommand`.

**Comment by FluffyDiscord** [comment]
Oh, the third option would actually make sense. I am closing this one, since it's probably the real culprit.
